# Generated by Django 5.2.1 on 2025-05-16 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_tourmap_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('label', models.CharField(blank=True, help_text='e.g., Best Seller, Popular', max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Top Destination',
                'verbose_name_plural': 'Top Destinations',
                'ordering': ['order'],
            },
        ),
    ]
