# Generated by Django 5.2.1 on 2025-05-22 10:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='overview',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
