# Generated by Django 5.2.1 on 2025-05-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_alter_destination_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topdestination',
            name='label',
            field=models.CharField(blank=True, help_text='e.g., Best Seller, Popular', max_length=255),
        ),
    ]
