# Generated by Django 5.2.1 on 2025-06-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
