# Generated by Django 5.2.1 on 2025-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_logo',
            field=models.FileField(blank=True, help_text='Upload SVG logo for best quality', null=True, upload_to='organization_logos/'),
        ),
    ]
