# Generated by Django 5.2.1 on 2025-06-07 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Logo identifier (e.g., main, dark, icon)', max_length=100)),
                ('logo', models.ImageField(upload_to='project/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'svg', 'jpg', 'jpeg'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Logo',
                'verbose_name_plural': 'Project Logos',
                'ordering': ['name'],
            },
        ),
    ]
