# Generated by Django 5.2.1 on 2025-06-07 16:59

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_projectlogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideOfTheYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(default='Guide of the Year', max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guide_awards/photos/')),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guide of the Year',
                'verbose_name_plural': 'Guides of the Year',
                'ordering': ['-year'],
                'unique_together': {('guide', 'year')},
            },
        ),
    ]
