# Generated by Django 5.2.1 on 2025-06-07 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_guideoftheyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='contact us', max_length=100)),
                ('title', models.CharField(default='Get in touch with us', max_length=200)),
                ('address', models.TextField()),
                ('customer_service_title', models.CharField(default='Customer Service', max_length=100)),
                ('careers_title', models.CharField(default='Careers', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='pages.contactinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='pages.contactinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('vimeo', 'Vimeo')], max_length=50)),
                ('url', models.URLField()),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='pages.contactinfo')),
            ],
        ),
    ]
