# Generated by Django 5.2.1 on 2025-06-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_aboutpage_faq_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='twitter_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='twitter_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='twitter_title',
            field=models.TextField(blank=True),
        ),
    ]
