# Generated by Django 5.2.1 on 2025-06-22 22:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_aboutpage_keywords_aboutpage_og_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('title', models.CharField(blank=True, help_text='e.g., Senior Desert Guide', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('expertise', models.CharField(blank=True, help_text='e.g., Sahara, Atlas Mountains', max_length=255)),
                ('languages', models.CharField(blank=True, help_text='e.g., English, French, Arabic, Tamazight', max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_guides', to='pages.aboutpage')),
            ],
            options={
                'verbose_name': 'Travel Guide',
                'verbose_name_plural': 'Travel Guides',
                'ordering': ['order'],
            },
        ),
    ]
