"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""
import dj_database_url

from pathlib import Path
from decouple import config, Csv
import os
# BASE DIRECTORIES
BASE_DIR = Path(__file__).resolve().parent.parent

# CUSTOM BOOLEAN CASTING FUNCTION
def str_to_bool(value):
    """Convert string to boolean, handling common string representations."""
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower().strip() in ('true', '1', 'yes', 'on')
    return bool(value)

# SECURITY SETTINGS
SECRET_KEY = config("SECRET_KEY")
DEBUG = True 
ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

# SITE CONFIGURATION
SITE_ID = 1
#DEFAULT_FROM_EMAIL = 'contact@okatrip.club'



# APPLICATION DEFINITIONS
INSTALLED_APPS = [
    "jazzmin",

    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    'django_extensions',
    'widget_tweaks',

    # Third-party apps
    "django_cleanup",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "ckeditor",
    "ckeditor_uploader",
    "meta",

    # Local apps
    "pages",
    "destinations",
    "blog",
    "users",
    "emailmarketing",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# DJANGO-ALLAUTH CONFIG
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = ["email"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

# EMAIL CONFIGURATION
#EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # Use an app password, not your actual Gmail password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# MIDDLEWARE CONFIGURATION
MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.gzip.GZipMiddleware",
]

# URLS & WSGI
ROOT_URLCONF = "core.urls"
WSGI_APPLICATION = "core.wsgi.application"

# TEMPLATES CONFIG
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'blog.context_processors.latest_posts',  # ← add this line
                'blog.context_processors.category_list',  # ← Add this line
                'blog.context_processors.tag_list',  # ← Add this line


            ],
        },
    },
]

# DATABASE CONFIGURATION
DATABASE_URL = config('DATABASE_URL')
db_config = dj_database_url.parse(DATABASE_URL)
neon_endpoint_id = db_config['HOST'].split('-pooler')[0] # Extracts 'ep-young-tooth-abxwmjb4'

DATABASES = {
    'default': {
        **db_config, # Unpack the dictionary parsed by dj_database_url
        'OPTIONS': {
            # `sslmode=require` should already be handled by dj_database_url if in URL,
            # but explicitly setting it doesn't hurt.
            'sslmode': 'require',
            # This is the crucial part for the "Endpoint ID is not specified" error.
            # Pass it as a single string to the 'options' key.
            'options': f'endpoint={neon_endpoint_id}'
        }
    }
}

# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# INTERNATIONALIZATION
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# DEFAULT PRIMARY KEY FIELD TYPE
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CKEDITOR CONFIGURATION
CKEDITOR_UPLOAD_PATH = "uploads/ck_editor/"
CKEDITOR_RESTRICT_BY_USER = False
CKEDITOR_REQUIRE_STAFF = False
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Image'],
            ['RemoveFormat', 'Source']
        ],
        'height': 300, # This sets the initial height
        'width': '100%',
        'skin': 'moono-lisa',
        'removePlugins': ','.join([ # <--- Modified this line
            'stylesheetparser',
            'resize',       # <--- Remove the manual resize handle if you only want autogrow
            'elementspath', # <--- Remove the status bar that shows element paths, often interferes with autogrow
        ]),
        'extraPlugins': ','.join([
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',     # <--- Ensure this is present
            'image',
            'uploadimage',
            'dialog',
            'widget',
            'lineutils',
            'clipboard',
        ]),
        # Autogrow specific settings:
        'autoGrow_minHeight': 200, # Minimum height (e.g., 200px)
        'autoGrow_maxHeight': 800, # Maximum height (optional, 0 means no limit)
        'autoGrow_bottomSpace': 50, # Space at the bottom, so scrollbars don't appear immediately
        'autoGrow_onStartup': True, # Grow on startup to fit initial content

        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
    }
}
# JAZZMIN ADMIN CONFIG
JAZZMIN_SETTINGS = {
    "show_ui_builder": True,
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "accent": "accent-info",
    "navbar": "navbar-cyan navbar-dark",
    "sidebar": "sidebar-light-info",
    "theme": "litera",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# # CLOUDFLARE R2 STORAGE SETTINGS
CLOUDFLARE_R2_CONFIG_OPTIONS = {
    "access_key": config("CLOUDFLARE_R2_ACCESS_KEY", default=""),
    "secret_key": config("CLOUDFLARE_R2_SECRET_KEY", default=""),
    "bucket_name": config("CLOUDFLARE_R2_BUCKET_NAME", default=""),
    "endpoint_url": config("CLOUDFLARE_R2_ENDPOINT_URL", default=""),
    "default_acl": "public-read",
    "signature_version": "s3v4",
}

STORAGES = {
    "default": {
        "BACKEND": "helpers.cloudflare.storages.MediaFilesStorage",
        "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# STATIC & MEDIA FILES
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = f"{config('CLOUDFLARE_R2_ENDPOINT_URL')}/{CLOUDFLARE_R2_CONFIG_OPTIONS['bucket_name']}/"
MEDIA_ROOT = ""  # Not needed for R2, as files are stored remotely

ACCOUNT_FORMS = {'signup': 'users.forms.CustomSignupForm'}
# ENVIRONMENT-SPECIFIC OVERRIDES
# Settings are now handled via .env file

# DEBUG OUTPUT
#print(f"DEBUG is set to: {DEBUG}")
#print(f"ALLOWED_HOSTS is set to: {ALLOWED_HOSTS}")
print(f"Database: {DATABASES}")
#print(f"STATIC_URL is set to: {STATIC_URL}")
#print(f"MEDIA_URL is set to: {MEDIA_URL}")
